name: scholar_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  firebase_core: ^2.16.0
  flutter_svg: ^2.0.7
  flutter:
    sdk: flutter
  firebase_auth: ^4.10.0
  fluttertoast: ^8.2.2
  modal_progress_hud_nsn: ^0.4.0
  chat_bubbles: ^1.5.0
  cloud_firestore: ^4.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
  assets:
    - assets/images/
    - assets/fonts/
