// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfWzCbp2LLVQciDRHMHAP5YXASx0C5y3o',
    appId: '1:972401022911:web:9f9269994d70e975f1730a',
    messagingSenderId: '972401022911',
    projectId: 'chat-app-7b47c',
    authDomain: 'chat-app-7b47c.firebaseapp.com',
    storageBucket: 'chat-app-7b47c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAO_auK2SX5ud8r40-2lUzC-j3Mcuk8gI',
    appId: '1:972401022911:android:1926b728c3294991f1730a',
    messagingSenderId: '972401022911',
    projectId: 'chat-app-7b47c',
    storageBucket: 'chat-app-7b47c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB01tYA9FBffCCVuEfoVjLGChTUx1f3LlM',
    appId: '1:972401022911:ios:9ab0a5462c0374aaf1730a',
    messagingSenderId: '972401022911',
    projectId: 'chat-app-7b47c',
    storageBucket: 'chat-app-7b47c.appspot.com',
    iosBundleId: 'com.example.scholarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB01tYA9FBffCCVuEfoVjLGChTUx1f3LlM',
    appId: '1:972401022911:ios:5753f220cb9a5b8bf1730a',
    messagingSenderId: '972401022911',
    projectId: 'chat-app-7b47c',
    storageBucket: 'chat-app-7b47c.appspot.com',
    iosBundleId: 'com.example.scholarApp.RunnerTests',
  );
}
